# Generated by Django 2.2.1 on 2019-06-08 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 13, 48, 53, 356708, tzinfo=utc)),
        ),
    ]
