# Generated by Django 2.2.1 on 2019-06-08 13:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190608_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='addedOn',
            field=models.DateTimeField(default=datetime.datetime(2019, 6, 8, 13, 55, 24, 11105, tzinfo=utc)),
        ),
    ]
